name: Go

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        go: [ "1.19", "1.20", "1.21" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Set up libheif library
        run: |
          sudo apt-get update && sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:strukturag/libde265
          sudo add-apt-repository -y ppa:strukturag/libheif
          sudo apt-get update && sudo apt-get install -y libheif-dev
      - name: Test
        run: |
          go test .